### ISSUE TITLE
迁移到 linux 平台

### ISSUE THREAD

**Issue by Endle** [wolfg1969/my-stars-pilot#3]
请问，这个小工具会迁移到 linux 平台吗？现阶段的障碍在哪里？

谢谢

**Comment by wolfg1969** [comment]
@Endle 改成纯 Python 了，不再依赖 KC 了。升级后需要运行下 mystars --update，生成的数据文件是 ~/./mystarspilot/mystars.db ，是个纯文本的 JSON 文件。
```
$ pip install mystarspilot --upgrade
```

**Comment by Endle** [comment]
在我的电脑上运行的很好，谢谢

**Comment by wolfg1969** [comment]
@Endle :-)
